// <auto-generated />
using System;
using DAB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAB.Data.Migrations
{
    [DbContext(typeof(DabDbContext))]
    [Migration("20240222210726_kkm")]
    partial class kkm
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DAB.Domain.Entities.Boisson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BoissonStock")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecetteId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecetteId1");

                    b.ToTable("Boissons");
                });

            modelBuilder.Entity("DAB.Domain.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("RecetteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecetteId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("DAB.Domain.Entities.Recette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recettes");
                });

            modelBuilder.Entity("DAB.Domain.Entities.RecetteIngredient", b =>
                {
                    b.Property<int>("Ingredient_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Recette_Id")
                        .HasColumnType("int");

                    b.Property<double>("Dose")
                        .HasColumnType("float");

                    b.Property<int>("Id_Recette_Ingrediant")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int?>("RecetteId")
                        .HasColumnType("int");

                    b.HasKey("Ingredient_Id", "Recette_Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecetteId");

                    b.ToTable("RecetteIngredients");
                });

            modelBuilder.Entity("DAB.Domain.Entities.Boisson", b =>
                {
                    b.HasOne("DAB.Domain.Entities.Recette", "Recette")
                        .WithMany()
                        .HasForeignKey("RecetteId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recette");
                });

            modelBuilder.Entity("DAB.Domain.Entities.Ingredient", b =>
                {
                    b.HasOne("DAB.Domain.Entities.Recette", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecetteId");
                });

            modelBuilder.Entity("DAB.Domain.Entities.RecetteIngredient", b =>
                {
                    b.HasOne("DAB.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId");

                    b.HasOne("DAB.Domain.Entities.Recette", "Recette")
                        .WithMany()
                        .HasForeignKey("RecetteId");

                    b.Navigation("Ingredient");

                    b.Navigation("Recette");
                });

            modelBuilder.Entity("DAB.Domain.Entities.Recette", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
